remote_theme: just-the-docs/just-the-docs
title: Atharva Nikam
description: Mechatronics Masterâ€™s student in Germany with a strong mechanical engineering background. Experienced in CAD design (CATIA V5, SolidWorks), FEA using ANSYS, and industrial project execution. Passionate about electrical drives, power electronics, and sustainable engineering solutions.
google_analytics: 
show_downloads: false
