remote_theme: pages-themes/merlot@v0.2.0

# Site Info
title: "Atharva Nikam"
description: "Mechatronics Engineer"
url: "https://atharvanikam.github.io"
baseurl: ""

# Profile Settings
author:
  name: "Atharva Nikam"
  avatar: "/iMAGE3.jpg"
  bio: "M.Sc. Mechatronics @ RWU Germany"
  location: "Germany"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/atharva-nikam1104/"

# This forces GitHub to see the index.md
include: ["index.md", "assets"]
