remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air" # 'air' is clean and white. Try 'contrast' for a sharper look.

title: "Atharva Nikam"
name: "Atharva Nikam"
bio: "Mechatronics M.Sc. Student | CAD & FEA Specialist"
location: "Weingarten, Germany"

# Sidebar info
author:
  name: "Atharva Nikam"
  avatar: "/iMAGE3.jpg" # Make sure your photo is named this
  bio: "M.Sc. Mechatronics @ RWU Germany"
  location: "Baden-WÃ¼rttemberg, Germany"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/atharva-nikam1104/"
